services:
  traefik:
    image: traefik:v3.3
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--accesslog=true"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/traefik.yml:ro
      - traefik:/certs
    env_file:
      - env/cloudflare.env
    networks:
      - web
    
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: userdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web
    expose:
      - "5432"
      
  ddns-updater:
    build: 
      context: ./ddns-updater
      dockerfile: ../dockerfiles/ddns-updater.dockerfile
    environment:
      - PING_INTERVAL=60
      - PING_URL=https://api.ipify.org?format=json
    env_file:
      - env/cloudflare.env
      - env/ddns-updater.env
    tty: true
    stdin_open: true
    networks:
      - web


  file-server:
    build: 
      context: ./file-server
      dockerfile: ../dockerfiles/file-server.dockerfile
    tty: true
    stdin_open: true
    depends_on:
      - postgres
      - traefik
    networks:
      - web
    volumes:
      - ./files:/app/uploads
      - sharing:/app/temp
      - traefik:/app/certs
      - secrets:/app/secrets
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.file-server.rule=HostSNI(`api.homeshare.pro`)"
      - "traefik.tcp.routers.file-server.entrypoints=websecure"
      - "traefik.tcp.routers.file-server.tls.passthrough=true"
      
    expose:
      - "443"

  web-interface:
    build:
      context: ./web-interface
      dockerfile: ../dockerfiles/web-interface.dockerfile
    networks:
      - web
    depends_on:
      - postgres
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-interface.rule=Host(`homeshare.pro`)"
      - "traefik.http.routers.web-interface.entrypoints=websecure"
      - "traefik.http.routers.web-interface.tls=true"
      - "traefik.http.routers.web-interface.tls.certresolver=letencrypt"
    expose:
      - "80"

volumes:
  pgdata:
    name: pgdata
  traefik:
    name: traefik
  secrets:
    name: secrets
  sharing:
    name: sharing

networks:
  web:
    name: web