api:
  dashboard: true
  debug: true
log:
  level: DEBUG
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: web
certificatesResolvers:
  letencrypt:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: changeme@changeme.org
      storage: /certs/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 60